# Generated by Django 5.1.5 on 2025-02-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalHabilitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_id', models.CharField(max_length=50, unique=True)),
                ('fecha_habilitado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_id', models.CharField(max_length=100)),
                ('usuario_id', models.CharField(max_length=100)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('nombre_global', models.CharField(blank=True, max_length=100, null=True)),
                ('contenido_mensaje', models.TextField()),
                ('respuesta_modelo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
